### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mrctito** [monkeylearn/hotel-review-analysis#4]
Dear sirs,

I am getting the following error, could you help me?
Thak you!

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\Marcos Tito\hotel_sentiment\hotel_sentiment\spiders\tripadvisor_spider.py", line 40, in parse_review
    item['stars'] = response.xpath('//span[@class="rate sprite-rating_s rating_s"]/img/@alt').extract()[0]
IndexError: list index out of range

**Comment by brusteca** [comment]
Hmmm, it seems that TripAdvisor has changed their site, so these xpath selectors don't work anymore. The class for the stars is no longer an image under `rate sprite-rating_s rating_s` but instead `ui_bubble_rating bubble_40`, with the number indicating the number of stars. I'll update the code when I have the time. In the meantime, try changing the xpath to see if you can get it to work. Pull requests are welcome!

**Comment by mrctito** [comment]
Thank you very much!

2017-06-26 11:08 GMT-03:00 brusteca <notifications@github.com>:

**Comment by qwIvan** [comment]
When will author update?

**Comment by brusteca** [comment]
Totally forgot about this issue. Just fixed it. TripAdvisor changed their whole site, so I updated `tripadvisor_spider.py` to work with the new site. Pagination in the hotels page doesn't work because it can't be done easily (it uses js fetching). Pagination in the reviews page of each hotel does work though (not with the most elegant method), so for a given hotel you'll get all the reviews.

Cheers!
